Update module with main logic into src/index.js and update README
dial-once/node-flat-camel pull request #1
Opened 2017-08-14 13:25 UTC by williamluang

2017-08-15 09:59 UTC, mrister requested changes

2017-08-15 09:59 UTC, mrister commented on README.md
> +There are no environment to set up, this module is ready to use.
there **is** no environment...

2017-08-15 09:59 UTC, mrister commented on package.json
> +    "flatten-obj": "^3.1.1",
this should not be a dev dependency since you use it in src/index.js, but a dependecy

2017-08-15 09:59 UTC, mrister commented on src/index.js
> +    if (Object.prototype.hasOwnProperty.call(cur, p)) {
what is someone would like to use the module but using properties that are down the prototype chain ?

2017-08-15 09:59 UTC, mrister commented on src/index.js
> +  if (Object(cur) !== cur) {
can you explain a bit what is the purpose if this check and why you use Object?

2017-08-15 09:59 UTC, mrister commented on src/index.js
> +module.exports = function (data, exclusions) {
arrow function ?

2017-08-15 09:59 UTC, mrister commented on src/index.js
> +module.exports = function (data, exclusions) {
do you need to export this at all since camelCase is the only exported function being used ?

2017-08-15 09:59 UTC, mrister commented on src/index.js
> +  for (const key of Object.keys(flattenedObj)) {
use Object.keys(flattenedObj)  before the for loop to skip looking up keys on every itereation

2017-08-15 09:59 UTC, mrister commented on src/index.js
> +    const regex = /\./gi;
suggestion HAS_DOT_REGEX

2017-08-15 09:59 UTC, mrister commented on test/index-spec.js
> +  it('should flatten object to camel-case style', () => {
would be nice to have more test cases, objects with prototypes, numbers, array, null and any other edge case you could think of.

2017-08-17 13:59 UTC, Spring3 commented on src/index.js
> +  for (const key of Object.keys(flattenedObj)) {
we checked that and it only looks there once

2017-08-17 14:00 UTC, Spring3 commented on src/index.js
> +  for (const key of Object.keys(flattenedObj)) {
`for of` looks once while plain `for` look calculates the source each iteration

2017-08-17 14:02 UTC, Spring3 commented on test/index-spec.js
> +  it('should flatten object to camel-case style', () => {
won't work for array. The purpose was to flatten plain objects

2017-08-17 14:06 UTC, Spring3 requested changes

2017-08-17 14:06 UTC, Spring3 commented on src/index.js
> +module.exports.camelCase = (obj) => {
@williamluang sorry for not mentioning this during our call. You only need this function. Other functions should not be included into the library.

2017-08-17 14:10 UTC, Spring3 commented on src/index.js
> +module.exports.camelCase = (obj) => {
Also maybe you could think of a way to create a small layer of abstraction and make it a place for configuration/initialization. For example to support not only env variables, but also plain settings object that will affect the way the library works. Not everyone configures its app using env vars prior to settings. And @mrister also mentioned this when he asked to have some ability to pass for example HASHING_KEY as a config property

2017-08-17 14:11 UTC, Spring3 commented on src/index.js
> +module.exports.camelCase = (obj) => {
In case you need some help, do not hesitate to ask

2017-08-18 15:01 UTC, williamluang commented on src/index.js
> +module.exports.camelCase = (obj) => {
Ok thank you, I need to document myself a bit but i'll ask you if there are things that I have trouble understanding !

2017-08-25 12:33 UTC, ofkindness approved these changes

2017-08-25 13:12 UTC, mrister requested changes

2017-08-25 13:12 UTC, mrister commented on src/index.js
> +  for (const key of Object.keys(flattenedObj)) {
nice to know!

2017-08-25 13:12 UTC, mrister commented on src/index.js
> +    const HAD_DOT_REGEX = /\./gi;
suggestion: HAS_DOT_REGEX

2017-08-25 13:12 UTC, mrister commented on src/index.js
> +    // if key contains dot
quite obvious from code, you can remove such comments

2017-08-25 13:12 UTC, mrister commented on test/index-spec.js
> +  it('should flatten object to camel-case style', () => {
Should be as noted in readme. but other cases would be nice

2017-08-28 11:35 UTC, Spring3 approved these changes
please add some info about supported object types and we are good to go

2017-08-28 16:02 UTC, ykhatal approved these changes

2017-09-04 22:32 UTC, jkernech requested changes
The README needs to be updated to be more consistent, to be more concise the description of the module as well as the documentation needs to be reworked

2017-09-04 22:32 UTC, jkernech commented on README.md
> +Exammples:
### Typo 
> Examples

2017-09-04 22:32 UTC, jkernech commented on README.md
>  Dial-Once
Not sure the meaning of this.. Why not use the module name ?

2017-09-04 22:32 UTC, jkernech commented on sonar-project.properties
> +sonar.projectVersion=0.0.0
This can be removed

2017-09-04 22:32 UTC, jkernech commented on src/index.js
> +module.exports.camelCase = (obj) => {
### Suggestion
> toCamelCase

2017-10-23 15:17 UTC, mrister approved these changes

2017-10-23 15:17 UTC, mrister commented on sonar-project.properties
> +sonar.projectKey=flat-camel
node-flat-camel ?

2017-10-23 15:17 UTC, mrister commented on src/index.js
> +      const CHAR_NEXT_TO_DOT = /\../gi;
there is no need to redefine the const for each for loop it can be moved up

2017-10-23 16:11 UTC, ykhatal approved these changes

2017-10-24 04:00 UTC, ofkindness approved these changes

2017-10-25 13:40 UTC, jkernech approved these changes
Aside from @mrister comment and the README.md format, all good

2017-10-25 14:14 UTC, merged